export const effectsData = {
  burn: {
    id: "burn",
    name: "Burn",
    icon: "🔥",
    description: "Deals fire damage over time.",
    duration: 3,
    type: "damageOverTime",
    damageType: "fire",
    tickDamagePercent: 0.05,
    statAffected: null,
    modifier: 0,
    canStack: false,
    applyLog: (targetName) => `${targetName} is engulfed in flames!`,
    tickLog: (targetName, dmg) => `${targetName} takes ${dmg} fire damage.`,
    expireLog: (targetName) => `${targetName} is no longer burning.`,
  },

  poison: {
    id: "poison",
    name: "Poison",
    icon: "☣︎",
    description: "Gradually reduces vitality each turn.",
    duration: 4,
    type: "damageOverTime",
    damageType: "toxic",
    tickDamagePercent: 0.04,
    statAffected: null,
    modifier: 0,
    canStack: false,
    applyLog: (targetName) => `${targetName} is poisoned!`,
    tickLog: (targetName, dmg) => `${targetName} suffers ${dmg} poison damage.`,
    expireLog: (targetName) => `${targetName} recovers from the poison.`,
  },

  bleed: {
    id: "bleed",
    name: "Bleed",
    icon: "🩸",
    description: "Loses health each turn from open wounds.",
    duration: 3,
    type: "damageOverTime",
    damageType: "physical",
    tickDamagePercent: 0.06,
    statAffected: null,
    modifier: 0,
    canStack: true,
    applyLog: (targetName) => `${targetName} starts bleeding!`,
    tickLog: (targetName, dmg) => `${targetName} loses ${dmg} blood damage.`,
    expireLog: (targetName) => `${targetName}'s bleeding stops.`,
  },

  stun: {
    id: "stun",
    name: "Stun",
    icon: "😵‍💫",
    description: "Prevents taking actions for one turn.",
    duration: 1,
    type: "debuff",
    statAffected: "actions",
    modifier: -1, // blocks 1 action
    tickDamagePercent: 0,
    canStack: false,
    applyLog: (targetName) => `${targetName} is stunned and can't move!`,
    tickLog: () => null,
    expireLog: (targetName) => `${targetName} regains consciousness.`,
  },

  regenerate: {
    id: "regenerate",
    name: "Regeneration",
    icon: "❤️",
    description: "Restores vitality each turn.",
    duration: 3,
    type: "healOverTime",
    tickHealPercent: 0.05,
    statAffected: "vitality",
    modifier: +0.05, // heals 5% per tick
    canStack: false,
    applyLog: (targetName) => `${targetName} begins regenerating health!`,
    tickLog: (targetName, heal) =>
      `${targetName} recovers ${heal} vitality through regeneration.`,
    expireLog: (targetName) => `${targetName}'s regeneration fades.`,
  },

  charm: {
    id: "charm",
    name: "Charm",
    icon: "💫",
    description: "Lowers the attack temporarily.",
    duration: 2,
    type: "debuff",
    statAffected: "attack",
    modifier: -0.25, // reduces attack by 25%
    canStack: false,
    applyLog: (targetName) => `${targetName} is charmed — thier attack will do less damage!`,
    tickLog: (targetName) => `${targetName}'s guard remains weakened.`,
    expireLog: (targetName) => `${targetName} regains composure and their guard returns.`,
  },

  defense_up: {
    id: "defense_up",
    name: "Defense Up",
    icon: "🛡️↑",
    description: "Increases the defense for few turns.",
    duration: 3,
    type: "debuff",
    statAffected: "defense",
    modifier: +1.15,
    canStack: false,
    applyLog: (targetName) => `${targetName} has it's defense increased!`,
    tickLog: (targetName) => `${targetName}'s guard remained increased!`,
    expireLog: (targetName) => `${targetName}'s guard returned to normal.`
  },

  defense_low: {
    id: "defense_low",
    name: "Defense Lowered",
    icon: "🛡️",
    description: "Decreases the defense for few turns.",
    duration: 3,
    type: "debuff",
    statAffected: "defense",
    modifier: -1.15,
    canStack: false,
    applyLog: (targetName) => `${targetName} has it's defense lowered!`,
    tickLog: (targetName) => `${targetName}'s guard remained lowered!`,
    expireLog: (targetName) => `${targetName}'s guard returned to normal.`
  }
};
